"""google provider added

Revision ID: 0929dbb1b059
Revises: 8d86d84c724e
Create Date: 2026-09-16 12:11:41.537709

"""

from typing import Sequence, Union

from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0929dbb1b059"
down_revision: Union[str, Sequence[str], None] = "8d86d84c724e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sso_connections",
        "provider",
        existing_type=postgresql.ENUM("azure_ad", name="sso_provider"),
        nullable=True,
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="sso_provider",
        new_values=["azure_ad", "google"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="sso_connections",
                column_name="provider",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="sso_provider",
        new_values=["azure_ad"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="sso_connections",
                column_name="provider",
            )
        ],
        enum_values_to_rename=[],
    )
    op.alter_column(
        "sso_connections",
        "provider",
        existing_type=postgresql.ENUM("azure_ad", name="sso_provider"),
        nullable=False,
    )
    # ### end Alembic commands ###
