"""initial_prolens_schema

Revision ID: ab405c83cdd5
Revises:
Create Date: 2026-09-15 14:53:23.808240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab405c83cdd5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("invited", "active", "suspended", name="user_status").create(op.get_bind())
    sa.Enum(
        "holiday",
        "milestone",
        "leave",
        "release",
        "team_event",
        name="calendar_event_type",
    ).create(op.get_bind())
    sa.Enum("sick", "casual", "vacation", name="leave_type").create(op.get_bind())
    sa.Enum("active", "suspended", name="org_status").create(op.get_bind())
    sa.Enum("low", "medium", "high", "urgent", name="priority_level").create(
        op.get_bind()
    )
    sa.Enum("to_do", "in_progress", "in_review", "done", name="entity_status").create(
        op.get_bind()
    )
    sa.Enum("active", "on_hold", "completed", name="project_status").create(
        op.get_bind()
    )
    sa.Enum("insert", "update", "delete", name="audit_action").create(op.get_bind())
    sa.Enum(
        "pending", "processing", "completed", "failed", name="report_job_status"
    ).create(op.get_bind())
    sa.Enum("report", "timeline", "summary", name="report_job_type").create(
        op.get_bind()
    )
    sa.Enum("on_track", "at_risk", "delayed", name="health_status").create(
        op.get_bind()
    )
    sa.Enum(
        "pending", "accepted", "expired", "revoked", name="invitation_status"
    ).create(op.get_bind())
    sa.Enum("super_admin", "admin", "manager", "employee", name="user_role").create(
        op.get_bind()
    )
    # Required for the GiST exclusion constraint on leave_logs (daterange
    # overlap + UUID equality needs btree_gist's operator class for UUID).
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # organizations, designations, and users form a 3-way FK cycle
    # (org.deleted_by/designation.deleted_by -> users.id, while
    # users.organization_id/designation_id -> organizations/designations).
    # Create all three table shells first (deleted_by columns un-constrained),
    # then add the deleted_by FKs once every table exists.
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "suspended", name="org_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "designations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_org_designation", "designations", ["organization_id", "name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("designation_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM(
                "super_admin",
                "admin",
                "manager",
                "employee",
                name="user_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "invited", "active", "suspended", name="user_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["designation_id"],
            ["designations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_superadmin_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_index(
        "idx_users_org_email",
        "users",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_index(
        "idx_users_org_role", "users", ["organization_id", "role"], unique=False
    )
    op.create_foreign_key(
        "organizations_deleted_by_fkey",
        "organizations",
        "users",
        ["deleted_by"],
        ["id"],
    )
    op.create_foreign_key(
        "designations_deleted_by_fkey", "designations", "users", ["deleted_by"], ["id"]
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            postgresql.ENUM(
                "insert", "update", "delete", name="audit_action", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_log_org_changed_at",
        "audit_log",
        ["organization_id", "changed_at"],
        unique=False,
    )
    op.create_index(
        "idx_audit_log_table_record",
        "audit_log",
        ["table_name", "record_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "leave_logs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "leave_type",
            postgresql.ENUM(
                "sick", "casual", "vacation", name="leave_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("user_id"), "="),
            (sa.text("daterange(start_date, end_date, '[]')"), "&&"),
            where=sa.text("deleted_at IS NULL"),
            using="gist",
            name="excl_leave_logs_no_overlap",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_leave_logs_org_date",
        "leave_logs",
        ["organization_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("client_name", sa.String(), nullable=True),
        sa.Column("client_contact", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active",
                "on_hold",
                "completed",
                name="project_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_jobs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column(
            "job_type",
            postgresql.ENUM(
                "report",
                "timeline",
                "summary",
                name="report_job_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "processing",
                "completed",
                "failed",
                name="report_job_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_s3_key", sa.String(length=500), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_report_jobs_org_status",
        "report_jobs",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_report_jobs_requested_by", "report_jobs", ["requested_by"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("theme", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "activities",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "project_id",
            sa.UUID(),
            nullable=True,
            comment="NULL = standalone operational activity, not tied to any project (AM-01)",
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "to_do",
                "in_progress",
                "in_review",
                "done",
                name="entity_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_leave_log_id",
            sa.UUID(),
            nullable=True,
            comment="System-generated from a leave log; deleting the leave log soft-deletes this row (LM-04)",
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "holiday",
                "milestone",
                "leave",
                "release",
                "team_event",
                name="calendar_event_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "end_time >= start_time", name="chk_calendar_event_timeline"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_leave_log_id"],
            ["leave_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_calendar_events_org_dates",
        "calendar_events",
        ["organization_id", "start_time", "end_time"],
        unique=False,
    )
    op.create_table(
        "features",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "to_do",
                "in_progress",
                "in_review",
                "done",
                name="entity_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invitations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "intended_role",
            postgresql.ENUM(
                "super_admin",
                "admin",
                "manager",
                "employee",
                name="user_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "accepted",
                "expired",
                "revoked",
                name="invitation_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "org_insight_snapshots",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("task_count", sa.Integer(), nullable=False),
        sa.Column("completed_task_count", sa.Integer(), nullable=False),
        sa.Column(
            "estimated_hours_total", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "actual_hours_total", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("time_variance_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "completion_rate_pct", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "health_status",
            postgresql.ENUM(
                "on_track",
                "at_risk",
                "delayed",
                name="health_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("performance_rank", sa.Integer(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_org_insight_snapshots_project_time",
        "org_insight_snapshots",
        ["project_id", "computed_at"],
        unique=False,
    )
    op.create_table(
        "project_members",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("added_by", sa.UUID(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["removed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_members_active",
        "project_members",
        ["project_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.create_table(
        "activity_assignees",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["removed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activity_assignees_active",
        "activity_assignees",
        ["activity_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.create_table(
        "feature_members",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["features.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["removed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_feature_members_active",
        "feature_members",
        ["feature_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.create_table(
        "tasks",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "to_do",
                "in_progress",
                "in_review",
                "done",
                name="entity_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "low",
                "medium",
                "high",
                "urgent",
                name="priority_level",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["features.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attachments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("feature_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("activity_id", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "\n            (\n                (CASE WHEN project_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN feature_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN task_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN activity_id IS NOT NULL THEN 1 ELSE 0 END)\n            ) = 1\n            ",
            name="chk_attachment_target_exclusive_arc",
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["features.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_attachments_activity", "attachments", ["activity_id"], unique=False
    )
    op.create_index(
        "idx_attachments_feature", "attachments", ["feature_id"], unique=False
    )
    op.create_index(
        "idx_attachments_project", "attachments", ["project_id"], unique=False
    )
    op.create_index("idx_attachments_task", "attachments", ["task_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("parent_comment_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("feature_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("activity_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "\n            (\n                (CASE WHEN project_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN feature_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN task_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN activity_id IS NOT NULL THEN 1 ELSE 0 END)\n            ) = 1\n            ",
            name="chk_comment_target_exclusive_arc",
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["features.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_comment_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comments_activity", "comments", ["activity_id"], unique=False)
    op.create_index("idx_comments_feature", "comments", ["feature_id"], unique=False)
    op.create_index("idx_comments_project", "comments", ["project_id"], unique=False)
    op.create_index("idx_comments_task", "comments", ["task_id"], unique=False)
    op.create_table(
        "task_assignees",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["removed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_task_assignees_active",
        "task_assignees",
        ["task_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.create_table(
        "time_logs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("activity_id", sa.UUID(), nullable=True),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "\n            (\n                (CASE WHEN task_id IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN activity_id IS NOT NULL THEN 1 ELSE 0 END)\n            ) = 1\n            ",
            name="chk_timelog_target_exclusive_arc",
        ),
        sa.CheckConstraint(
            "duration_minutes <= 1440", name="chk_timelog_duration_max_24h"
        ),
        sa.CheckConstraint(
            "duration_minutes > 0", name="chk_timelog_duration_positive"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_timelogs_org_date",
        "time_logs",
        ["organization_id", "log_date"],
        unique=False,
    )
    op.create_index(
        "idx_timelogs_user_date", "time_logs", ["user_id", "log_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_timelogs_user_date", table_name="time_logs")
    op.drop_index("idx_timelogs_org_date", table_name="time_logs")
    op.drop_table("time_logs")
    op.drop_index(
        "idx_task_assignees_active",
        table_name="task_assignees",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.drop_table("task_assignees")
    op.drop_index("idx_comments_task", table_name="comments")
    op.drop_index("idx_comments_project", table_name="comments")
    op.drop_index("idx_comments_feature", table_name="comments")
    op.drop_index("idx_comments_activity", table_name="comments")
    op.drop_table("comments")
    op.drop_index("idx_attachments_task", table_name="attachments")
    op.drop_index("idx_attachments_project", table_name="attachments")
    op.drop_index("idx_attachments_feature", table_name="attachments")
    op.drop_index("idx_attachments_activity", table_name="attachments")
    op.drop_table("attachments")
    op.drop_table("tasks")
    op.drop_index(
        "idx_feature_members_active",
        table_name="feature_members",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.drop_table("feature_members")
    op.drop_index(
        "idx_activity_assignees_active",
        table_name="activity_assignees",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.drop_table("activity_assignees")
    op.drop_index(
        "idx_project_members_active",
        table_name="project_members",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.drop_table("project_members")
    op.drop_index(
        "idx_org_insight_snapshots_project_time", table_name="org_insight_snapshots"
    )
    op.drop_table("org_insight_snapshots")
    op.drop_table("invitations")
    op.drop_table("features")
    op.drop_index("idx_calendar_events_org_dates", table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_table("activities")
    op.drop_table("user_preferences")
    op.drop_index("idx_report_jobs_requested_by", table_name="report_jobs")
    op.drop_index("idx_report_jobs_org_status", table_name="report_jobs")
    op.drop_table("report_jobs")
    op.drop_table("projects")
    op.drop_index("idx_leave_logs_org_date", table_name="leave_logs")
    op.drop_table("leave_logs")
    op.drop_index("idx_audit_log_table_record", table_name="audit_log")
    op.drop_index("idx_audit_log_org_changed_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_constraint(
        "designations_deleted_by_fkey", "designations", type_="foreignkey"
    )
    op.drop_constraint(
        "organizations_deleted_by_fkey", "organizations", type_="foreignkey"
    )
    op.drop_index("idx_users_org_role", table_name="users")
    op.drop_index(
        "idx_users_org_email",
        table_name="users",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_superadmin_email",
        table_name="users",
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.drop_table("users")
    op.drop_index("uq_org_designation", table_name="designations")
    op.drop_table("designations")
    op.drop_table("organizations")
    sa.Enum("super_admin", "admin", "manager", "employee", name="user_role").drop(
        op.get_bind()
    )
    sa.Enum("pending", "accepted", "expired", "revoked", name="invitation_status").drop(
        op.get_bind()
    )
    sa.Enum("on_track", "at_risk", "delayed", name="health_status").drop(op.get_bind())
    sa.Enum("report", "timeline", "summary", name="report_job_type").drop(op.get_bind())
    sa.Enum(
        "pending", "processing", "completed", "failed", name="report_job_status"
    ).drop(op.get_bind())
    sa.Enum("insert", "update", "delete", name="audit_action").drop(op.get_bind())
    sa.Enum("active", "on_hold", "completed", name="project_status").drop(op.get_bind())
    sa.Enum("to_do", "in_progress", "in_review", "done", name="entity_status").drop(
        op.get_bind()
    )
    sa.Enum("low", "medium", "high", "urgent", name="priority_level").drop(
        op.get_bind()
    )
    sa.Enum("active", "suspended", name="org_status").drop(op.get_bind())
    sa.Enum("sick", "casual", "vacation", name="leave_type").drop(op.get_bind())
    sa.Enum(
        "holiday",
        "milestone",
        "leave",
        "release",
        "team_event",
        name="calendar_event_type",
    ).drop(op.get_bind())
    sa.Enum("invited", "active", "suspended", name="user_status").drop(op.get_bind())
    # ### end Alembic commands ###
