"""tenant_id made nullable

Revision ID: f0ac6e3a3d90
Revises: 114124ac3705
Create Date: 2026-09-20 21:37:41.136793

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0ac6e3a3d90"
down_revision: Union[str, Sequence[str], None] = "114124ac3705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sso_connections",
        "tenant_id",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sso_connections",
        "tenant_id",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    # ### end Alembic commands ###
